### PR TITLE
Add script for Surviving Mars (GOG).

### PR DESCRIPTION
**Pull request by dawnmist**
I've based the script on what I was seeing in several other play scripts, but if there is something that needs to be cleaned up a bit just let me know.

I am not sure what additional packages are needed, as it seemed that I already had everything needed for this installed at the time I tried the original linux installer for the game. So the dependency list is potentially incomplete, but GOG wasn't listing any particular packages as necessary for it.

### CODE REVIEW

**Comment by vv221** [comment]
Thanks for this one ;)

I see you included the libSSL 1.0.0, are you sure it is needed by this game or did you just copy this from another script? It seems strange to me that a game published recently would use this obsolete library.

**Comment by dawnmist** [comment]
I needed it to be able to get the original installation to actually run. It's been linked against libssl.so.1.0.0 & libcrypto.so.1.0.0:
```sh
$> ldd /usr/local/share/games/surviving-mars/MarsGOG 
	linux-vdso.so.1 (0x00007fff61668000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007ffaa4232000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007ffaa402e000)
	libcurl-gnutls.so.4 => /usr/lib/x86_64-linux-gnu/libcurl-gnutls.so.4 (0x00007ffaa3da8000)
	libopenal.so.1 => /usr/lib/x86_64-linux-gnu/libopenal.so.1 (0x00007ffaa3b09000)
	libssl.so.1.0.0 => not found
	libcrypto.so.1.0.0 => not found
	libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007ffaa37cb000)
	libXext.so.6 => /usr/lib/x86_64-linux-gnu/libXext.so.6 (0x00007ffaa35b9000)
	libXrender.so.1 => /usr/lib/x86_64-linux-gnu/libXrender.so.1 (0x00007ffaa33af000)
	libXrandr.so.2 => /usr/lib/x86_64-linux-gnu/libXrandr.so.2 (0x00007ffaa31a4000)
	libXt.so.6 => /usr/lib/x86_64-linux-gnu/libXt.so.6 (0x00007ffaa2f3b000)
	libSDL2-2.0.so.0 => not found
	libpops_api.so => not found
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007ffaa2bba000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007ffaa2827000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007ffaa260f000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007ffaa2255000)
	/lib64/ld-linux-x86-64.so.2 (0x00007ffaa4450000)
	libnghttp2.so.14 => /usr/lib/x86_64-linux-gnu/libnghttp2.so.14 (0x00007ffaa202f000)
	libidn2.so.0 => /usr/lib/x86_64-linux-gnu/libidn2.so.0 (0x00007ffaa1e12000)
	librtmp.so.1 => /usr/lib/x86_64-linux-gnu/librtmp.so.1 (0x00007ffaa1bf5000)
	libssh2.so.1 => /usr/lib/x86_64-linux-gnu/libssh2.so.1 (0x00007ffaa19c8000)
	libpsl.so.5 => /usr/lib/x86_64-linux-gnu/libpsl.so.5 (0x00007ffaa17b7000)
	libnettle.so.6 => /usr/lib/x86_64-linux-gnu/libnettle.so.6 (0x00007ffaa1580000)
	libgnutls.so.30 => /usr/lib/x86_64-linux-gnu/libgnutls.so.30 (0x00007ffaa1215000)
	libgssapi_krb5.so.2 => /usr/lib/x86_64-linux-gnu/libgssapi_krb5.so.2 (0x00007ffaa0fc9000)
	libkrb5.so.3 => /usr/lib/x86_64-linux-gnu/libkrb5.so.3 (0x00007ffaa0cee000)
	libk5crypto.so.3 => /usr/lib/x86_64-linux-gnu/libk5crypto.so.3 (0x00007ffaa0abc000)
	libcom_err.so.2 => /lib/x86_64-linux-gnu/libcom_err.so.2 (0x00007ffaa08b8000)
	libldap_r-2.4.so.2 => /usr/lib/x86_64-linux-gnu/libldap_r-2.4.so.2 (0x00007ffaa0666000)
	liblber-2.4.so.2 => /usr/lib/x86_64-linux-gnu/liblber-2.4.so.2 (0x00007ffaa0457000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007ffaa0239000)
	libsndio.so.6.1 => /usr/lib/x86_64-linux-gnu/libsndio.so.6.1 (0x00007ffaa0029000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007ffa9fe21000)
	libatomic.so.1 => /usr/lib/x86_64-linux-gnu/libatomic.so.1 (0x00007ffa9fc19000)
	libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007ffa9f9f1000)
	libSM.so.6 => /usr/lib/x86_64-linux-gnu/libSM.so.6 (0x00007ffa9f7e9000)
	libICE.so.6 => /usr/lib/x86_64-linux-gnu/libICE.so.6 (0x00007ffa9f5cc000)
	libunistring.so.2 => /usr/lib/x86_64-linux-gnu/libunistring.so.2 (0x00007ffa9f24b000)
	libhogweed.so.4 => /usr/lib/x86_64-linux-gnu/libhogweed.so.4 (0x00007ffa9f015000)
	libgmp.so.10 => /usr/lib/x86_64-linux-gnu/libgmp.so.10 (0x00007ffa9ed91000)
	libgcrypt.so.20 => /lib/x86_64-linux-gnu/libgcrypt.so.20 (0x00007ffa9ea75000)
	libp11-kit.so.0 => /usr/lib/x86_64-linux-gnu/libp11-kit.so.0 (0x00007ffa9e748000)
	libtasn1.so.6 => /usr/lib/x86_64-linux-gnu/libtasn1.so.6 (0x00007ffa9e535000)
	libkrb5support.so.0 => /usr/lib/x86_64-linux-gnu/libkrb5support.so.0 (0x00007ffa9e329000)
	libkeyutils.so.1 => /lib/x86_64-linux-gnu/libkeyutils.so.1 (0x00007ffa9e125000)
	libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007ffa9df0e000)
	libsasl2.so.2 => /usr/lib/x86_64-linux-gnu/libsasl2.so.2 (0x00007ffa9dcf3000)
	libasound.so.2 => /usr/lib/x86_64-linux-gnu/libasound.so.2 (0x00007ffa9d9f5000)
	libbsd.so.0 => /lib/x86_64-linux-gnu/libbsd.so.0 (0x00007ffa9d7de000)
	libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007ffa9d5da000)
	libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007ffa9d3d4000)
	libuuid.so.1 => /lib/x86_64-linux-gnu/libuuid.so.1 (0x00007ffa9d1cd000)
	libgpg-error.so.0 => /lib/x86_64-linux-gnu/libgpg-error.so.0 (0x00007ffa9cfad000)
	libffi.so.6 => /usr/lib/x86_64-linux-gnu/libffi.so.6 (0x00007ffa9cda4000)
```
The game installer provides the libopenal.so.1, libpops_api.so and libSDL2-2.0.so.0, but not the libssl or libcrypto libraries.

**Comment by vv221** [comment]
Thanks for the confirmation, I’m going to merge it soon.

**Comment by dawnmist** [comment]
I suspect that the reason for it using the old lib is for Ubuntu 14.04 compatibility, as GoG list it as supported on Ubuntu 14.04, Ubuntu 16.04, Ubuntu 18.04. :)

**Comment by vv221** [comment]
This merge request has been cloned on our main repository: https://framagit.org/vv221/play.it/merge_requests/64

**Comment by dawnmist** [comment]
They have just today released a free dlc pack for Surviving Mars. Should those all also be merged into the installer as optional packs?

If so, please give me a day to update the merge request to include the dlc pack. If not, do you have an example for a package that simply adds data files to the game?

**Comment by vv221** [comment]
The best way to handle DLC is by building a dedicated package, usually via another script. See for example:
https://framagit.org/vv221/play.it/blob/master/play.it-2/games/play-darkest-dungeon.sh
https://framagit.org/vv221/play.it/blob/master/play.it-2/games/play-darkest-dungeon-the-shieldbreaker.sh
https://framagit.org/vv221/play.it/blob/master/play.it-2/games/play-darkest-dungeon-the-crimson-court.sh

But you can still do it "the old way", by including it in the main game packages, like you did for Baldur’s Gate Siege of Dragonspear.

Anyway, I will let you the time to handle this new DLC before merging your pull request.

**Comment by dawnmist** [comment]
Thank you.

The pack simply adds a file to the Dlc directory inside the game's data directory (and another license directory to docs). What I am finding is that it installs into the `/usr/local/share/games/surviving-mars/Dlc` directory correctly, but the `~/.local/share/play.it-2/prefixes/surviving-mars/Dlc` directory does not get updated when running the game again to add a symlink for the new Dlc file. So it isn't available in-game unless I remove the existing prefixes/surviving-mars directory so that the whole directory gets recreated.

Is there a reason why the files inside the Dlc directory are themselves symlinked instead of symlinking the Dlc directory itself (which would then have automatically picked up the new file)? Or is there anything I can do to indicate that the current prefixes/surviving-mars directory should be refreshed so that it adds the symlink for the new Dlc file?

**Comment by vv221** [comment]
The lack of automatic prefix refresh is a long standing issue, we don’t have a reliable solution yet.
Removing the prefix to force its generation again is the advised method until we find something better.

I’m going to open an issue about this in [our bug tracker](https://framagit.org/vv221/play.it/issues).

**Comment by dawnmist** [comment]
Ok :).

The additional file I pushed earlier today adds support for the new DLC as a separate package then. This should be ready to use. :)

**Comment by vv221** [comment]
Merged into master.

**Pull request closed without merging**
